pipeline{
    agent any

    stages{
            stage ('build'){
                steps{
                    sh '''
                    ls
                    cat file.txt
                    '''
                }
            }
            stage ('test'){
                steps{
                    sh 'echo "test finished " '
                }
            }
            stage ('release'){
                steps{
                  sh 'echo "release finished " '
                }
            }




    }



}